name: IAS Scan
on:
  push:
    branches: [ master ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - id: my-scan
        uses: rapid7/insightappsec-scan-github-actions@v1.3.0
        with:
          region: "us2"
          api-key: ${{ secrets.IAS_API_KEY }}
          scan-config-id: "a56273cd-26e6-4f6f-9ac6-32aedfc20e33"
          #vuln-query: "vulnerability.vulnerabilityScore > 4"
      - name: Upload findings
        if: always()
        run: echo "${{ steps.my-scan.outputs.scan-findings }}"
        
        
